# Claude Code Hooks Configuration for MCP Bridge

[hooks.pre_tool_use]
command = "python3 /Users/erik/Desktop/claude-multiagent-system/mcp_bridge.py pre_tool_use"
enabled = true
description = "Intercept before tool execution for MCP coordination"

[hooks.post_tool_use]
command = "python3 /Users/erik/Desktop/claude-multiagent-system/mcp_bridge.py post_tool_use"
enabled = true
description = "Process tool results for MCP logging"

[hooks.notification]
command = "python3 /Users/erik/Desktop/claude-multiagent-system/mcp_bridge.py notification"
enabled = true
description = "Capture Claude notifications for MCP"

[hooks.stop]
command = "python3 /Users/erik/Desktop/claude-multiagent-system/mcp_bridge.py stop"
enabled = true
description = "Handle session end for MCP cleanup"
