# Pre-commit hooks for Claude Multi-Agent System
# Run: pre-commit install
# Manual run: pre-commit run --all-files

repos:
  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=100]

  # Python linter
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          --max-line-length=100,
          --ignore=E203 W503 E501,  # Black compatibility
          --exclude=.git __pycache__ venv .venv
        ]

  # Import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements  # Check for Python debugger imports
      - id: check-docstring-first

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-ll, --skip=B101]  # Skip assert_used test

  # Type checking (optional, comment out if too strict)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]

  # Markdown linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Shell script linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

# Configuration
default_language_version:
  python: python3.11

exclude: |
  (?x)^(
    .*\.egg-info/.*|
    \.git/.*|
    \.tox/.*|
    dist/.*|
    build/.*|
    venv/.*|
    \.venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    node_modules/.*|
    \.claude/.*
  )$

fail_fast: false
